# ruff: noqa: E501,I001
"""Generate the DIMER multi-model image-classification workshop notebook.

Besides the cells of ``multimodel_image_classification_workshop_source.py`` the notebook carries the hash
locks of its two isolated model environments byte-for-byte, in its carrier cell (id ``uvcarrier``), and
verifies their SHA-256 before use:

* ``common`` <- ``tools/image-workshop-common-requirements.lock``
* ``swin``   <- ``tools/image-workshop-swin-requirements.lock``

(``uv pip compile --generate-hashes`` for CPython 3.12 on ``x86_64-manylinux_2_28``, wheels only).

No notebook line may exceed ``LINE_LIMIT`` characters, so the Colab editor never stalls on one. Carried
locks are written as implicitly concatenated runs of pieces of at most ``PIECE_LIMIT`` characters, split at
line boundaries, and a long string assignment in a source cell (the embedded photo manifest) is rewritten as
a parenthesised run of pieces whose ``ast.literal_eval`` value is asserted equal to the original.
``--check`` fails when the notebook differs from the cells or from either carried lock.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import re
from pathlib import Path

from multimodel_image_classification_workshop_source import CELLS

NOTEBOOK_NAME = "DIMER_MultiModel_Image_Classification_Workshop.ipynb"
TOOLS = Path(__file__).resolve().parent
LOCKS = {
    "common": TOOLS / "image-workshop-common-requirements.lock",
    "swin": TOOLS / "image-workshop-swin-requirements.lock",
}
PIECE_LIMIT = 1000
LINE_LIMIT = 2000
REVISION = "0.3.0-candidate"
ICR_FIXES = ["ICR-01", "ICR-02", "ICR-03", "ICR-04", "ICR-05", "ICR-06", "ICR-07", "ICR-08"]
STRING_ASSIGNMENT = re.compile(r'^(?P<indent>\s*)(?P<name>[A-Za-z_][A-Za-z0-9_]*) = (?P<literal>"[^"\\]*")$')


def pieces(text, limit=PIECE_LIMIT):
    """Split text at line boundaries into pieces of at most ``limit`` characters (a longer line is cut)."""
    out = []
    current = ""
    for line in text.splitlines(keepends=True):
        while len(line) > limit:
            if current:
                out.append(current)
                current = ""
            out.append(line[:limit])
            line = line[limit:]
        if current and len(current) + len(line) > limit:
            out.append(current)
            current = ""
        current += line
    if current:
        out.append(current)
    return out


def split_long_literals(source):
    """Rewrite each over-long ``NAME = "..."`` line as a parenthesised run of pieces of equal value."""
    lines = []
    for line in source.split("\n"):
        match = STRING_ASSIGNMENT.match(line) if len(line) > PIECE_LIMIT else None
        if match is None:
            lines.append(line)
            continue
        value = ast.literal_eval(match["literal"])
        indent = match["indent"]
        run = [f"{indent}{match['name']} = ("]
        run += [f"{indent}    {json.dumps(value[i:i + PIECE_LIMIT])}" for i in range(0, len(value), PIECE_LIMIT)]
        run.append(f"{indent})")
        expression = "\n".join(run).split(" = ", 1)[1]
        if ast.literal_eval(expression) != value:
            raise SystemExit(f"split literal {match['name']} does not reproduce the original value")
        lines.extend(run)
    return "\n".join(lines)


def carried_locks():
    texts = {}
    for name, path in LOCKS.items():
        data = path.read_bytes()
        if b"\r" in data:
            raise SystemExit(f"{path} must use LF line endings")
        texts[name] = data.decode("utf-8")
    return texts


def lock_hashes(texts):
    return {name: hashlib.sha256(text.encode("utf-8")).hexdigest() for name, text in texts.items()}


def carrier_source(texts):
    lines = [
        "# @title Carried hash locks of the model environments",
        "# Generated by tools/build_multimodel_image_classification_workshop.py from",
        "# tools/image-workshop-<env>-requirements.lock; do not edit by hand.",
        "import hashlib",
        "",
        "CARRIED_LOCKS = {",
    ]
    for name, text in texts.items():
        lines.append(f" {name!r}: (")
        lines.extend(f"  {piece!r}" for piece in pieces(text))
        lines.append(" ),")
    lines.append("}")
    lines.append("LOCK_SHA256 = {")
    lines.extend(f" {name!r}: {digest!r}," for name, digest in lock_hashes(texts).items())
    lines.append("}")
    lines += [
        "LOCK_PATHS = {}",
        "for name, text in CARRIED_LOCKS.items():",
        "    path = WORK_ROOT / 'uv' / f'requirements-{name}.lock.txt'",
        "    path.parent.mkdir(parents=True, exist_ok=True)",
        "    path.write_text(text, encoding='utf-8', newline='\\n')",
        "    if hashlib.sha256(path.read_bytes()).hexdigest() != LOCK_SHA256[name]:",
        "        raise RuntimeError('Carried lock integrity failure: ' + name)",
        "    LOCK_PATHS[name] = path",
        "print('Carried hash locks verified:', sorted(LOCK_PATHS))",
    ]
    return "\n".join(lines)


def build_notebook():
    rendered = []
    texts = carried_locks()
    index = 0
    for cell in CELLS:
        source = carrier_source(texts) if cell.get("carrier") else split_long_literals(cell["source"])
        # Cells added after 0.2.0 carry their own id, so the numbered ids of the original cells do not move.
        cell_id = cell.get("id") or f"dimer-image-workshop-{index:02d}"
        if not cell.get("id"):
            index += 1
        too_long = [n for n, line in enumerate(source.split("\n"), 1) if len(line) > LINE_LIMIT]
        if too_long:
            raise SystemExit(f"cell {cell_id}: line(s) {too_long} exceed {LINE_LIMIT} characters")
        base = {
            "id": cell_id,
            "metadata": cell.get("metadata", {}),
            "source": source.splitlines(keepends=True),
        }
        if cell["kind"] == "markdown":
            rendered.append({"cell_type": "markdown", **base})
        else:
            rendered.append({"cell_type": "code", "execution_count": None, "outputs": [], **base})
    return {
        "cells": rendered,
        "metadata": {
            "accelerator": "GPU",
            "colab": {"gpuType": "T4", "provenance": []},
            "dimer": {
                "canonical_runtime": "NVIDIA Tesla T4",
                "capability": "multi-model-image-classification",
                "carrier": "common-probe comparative transfer-classification workshop",
                "clean_runtime_evidence": "pending",
                "credentials_required": False,
                "dataset": "six-species CC0 iNaturalist bird corpus",
                "default_tier": "STANDARD",
                "notebook_mode": "WORKSHOP",
                "notebook_profile": "E2E",
                "notebook_spec": "2.1",
                "release_status": "candidate",
                "standalone": True,
                "worker_required": False,
                "generated_from": {
                    "repository": "kurtvalcorza/vit-classification-pipeline",
                    "source": "tools/multimodel_image_classification_workshop_source.py",
                    "generator": "tools/build_multimodel_image_classification_workshop.py",
                },
                "carried_locks": {
                    name: {"source": f"tools/{LOCKS[name].name}", "sha256": digest}
                    for name, digest in lock_hashes(texts).items()
                },
                "runtime_environment": {
                    "platform": "Linux x86_64 only (Google Colab, Kaggle, Linux Jupyter)",
                    "python": "CPython 3.12.12 (uv managed)",
                    "uv": "0.12.15 (wheel pinned by size and SHA-256)",
                    "install": "uv pip install --require-hashes --only-binary :all: -r requirements-<env>.lock.txt",
                    "kernel_installs": "none; no restart",
                },
                "review_revisions": [
                    {
                        "review": "docs/reviews/2026-09-27-notebook-review/DIMER_Image_Classification_Notebook_Review.md",
                        "revision": "0.2.0-candidate",
                        "fixed": ICR_FIXES,
                    },
                    {
                        "revision": REVISION,
                        "date": "2026-10-03",
                        "base_commit": "c3f5030f58871447700dea5a0fecdec0446a9191",
                        "change": "uv isolated environment: the model environments are hash-locked CPython 3.12.12 venvs built by a pinned uv wheel and installed with --require-hashes --only-binary :all:; no kernel install and no restart; no cell line over 2,000 characters; Linux x86_64 only",
                        "fixes_kept": ICR_FIXES,
                    },
                ],
            },
            "kernelspec": {"display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python"},
            "workshop_revision": REVISION,
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def serialized():
    return json.dumps(build_notebook(), indent=1, ensure_ascii=False) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    out = args.out or repo / "tutorials" / NOTEBOOK_NAME
    content = serialized()
    if args.check:
        if not out.exists() or out.read_text(encoding="utf-8") != content:
            raise SystemExit(f"STALE: {out}; regenerate the workshop notebook")
        print(f"OK: {out}")
        return 0
    out.write_text(content, encoding="utf-8", newline="\n")
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
